config/routes.rb
Termz::Application.routes.draw do
devise_for :users
  

  
   root to: 'pages#home'

  

  resources :users do
      resources :projects do
            resources :translations do
               collection { post :import }
            end
      end
  end

 
  

  get "pages/home"

  get "pages/about"

  get "pages/contact"

  get "pages/search"

      
  match '/home', to: 'pages#home'
  match '/about', to: 'pages#about'
  match '/contact', to: 'pages#contact'
  match '/search', to: 'pages#search'

  resources :domains

 

   

end

app/models/translation.rb
# == Schema Information
#
# Table name: translations
#
#  id             :integer          not null, primary key
#  source_lang_id :integer
#  source_content :string(255)
#  target_lang_id :integer
#  target_content :string(255)
#  domain_id      :integer
#  owner_id       :integer
#  approval_id    :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  project_id     :integer
#  is_public      :boolean          default(TRUE)
#  is_term        :boolean          default(TRUE)
#  source_id      :integer
#

class Translation < ActiveRecord::Base




Translation::ISO_3166_SEPARATOR = "-"

  attr_accessible :approval_id, :domain_id, :owner_id, :project_id, :source_content, :source_lang_id, :target_content, :target_lang_id, :source_id

  validates_presence_of :source_content, :source_lang_id, :target_content, :target_lang_id, :domain_id

  #user
    belongs_to :owner, :class_name => 'User'

    belongs_to :source_lang, :class_name => 'Language'
     belongs_to :target_lang, :class_name => 'Language'

 	#project
 	belongs_to :project

 	belongs_to :approval
	belongs_to :domain

 	belongs_to :source

 	def self.set_ids(user, project)
 		@current_user = user
 		@current_project = project
 	end



 	def self.import(file)
 		#MAKE SURE LANGUAGES UP TO DATE

 		logger = Logger.new('importlog.log')

 		### DO DATABASE RAKE TASK TO SET UP LANGUAGES + DOMAINS FIRST!!!!!!!!!


 		###
 		#MAKE THIS A GEM IMPORTTERMZCSV?
 		###deal with variations in headers deDE enUS etc
 		###deal with 3 digit ISO CODES
 		### What if DOMAIN NAME IN FILE NAME IS NOT IN DB??


 		###
 		# GET CURRENT USER AND PROJECT ID WHEN FORM IS UPLOADED (IN IMPORT CONTROLLER ACTION??)


 		#CSV has headers: source_lang, target_language, source
 		#Take source_language look up id in Language table and assign to source_lang_id and same for target
 		#source is ; delimited.. add to Source iD 
 		# finally go to Associates table add new Translation ID to source ID
 		case File.extname(file.original_filename)
 		when ".csv"
 			#get header information as array 
 			#file.path
 			header_flds = CSV.read(file.path)[0]
 			if header_flds.count == 3
 				#TODO: try to find by iso code otherwise default to id 1000 'un' to id 1000 'un' 
 				begin
 					source_lang_id = Language.find_by_iso_code(correct_iso(header_flds[0])).id 
 					target_lang_id = Language.find_by_iso_code(correct_iso(header_flds[1])).id
 				rescue Exception => e
 					logger.error "Incorrect headers/ISO Code not in database: #{e}" + "  " + Time.now

 				end	
 			end	
 			#rtns array of hashes with new 
 			#domain based on filename format DOMAIN_
 				domain_code = get_domain_code(file.original_filename) 			
 				domain_id = Domain.find_by_code(domain_code).id


 				trans = SmarterCSV.process(file.path, :user_provided_headers => [:source_content, :target_content, :url]) do |arr|
 								#TODO: do not create source if blank url 
 								source_id = Source.create(arr.first.slice(:url)).id if arr.first.has_value?(:url)
 								trans_id = Translation.create(
 											arr.first.slice(:source_content, :target_content).merge(
 												{  :source_lang_id => source_lang_id, 
 												   :target_lang_id => target_lang_id, 
 												   :domain_id => domain_id,
 												   :source_id => source_id,
 												   :owner_id => @current_user.id,
 												   :project_id => @current_project.id
 												}	
 												)).id

 								
 								
 				 end
 	

		
 			#for console work:
 			# trans = SmarterCSV.process('tmp/LIEBHERR.csv', :user_provided_headers => [:source_content, :target_content, :source]) do |arr| puts arr.first.slice(:source).inspect end	
 			# trans = SmarterCSV.process('tmp/LIEBHERR.csv', :user_provided_headers => [:source_content, :target_content, :url]) do |arr| Source.create( arr.first.slice(:url)) end
 		else #for case block
 			raise "Unknown file type: #{file.original_filename}"	
 		end	

 	end 	


 	#should take an input which can DE de-AT de_At deCH (and all cases) and returns ISO code.
 	#PREREQUISITE - standard codes de-de or de must be in Domains table
 	#RETURNS - The iso-code which is in the table as a string, either 5 digit XX-XX or 2 digit XX 
 	def self.correct_iso(field)
 		case field.size
 		when 5
 			if ["-", "_"].include?(field[2])
				field[2] = ISO_3166_SEPARATOR
 			 	return field.downcase
 			else
 				raise "Formatting error"
 			end 
 		when 4
 			#does field only consist of \ws? if so add a "_"
 			if field.scan(/\w+/).include?(field)
 				field.insert(2, ISO_3166_SEPARATOR)
 				return field.downcase
 			else 
 				raise "Formatting Error"
 			end  	
 		when 2
 			# ISO 639-1
 			if field.scan(/\w+/).include?(field)
 				return field.downcase
 			else
 				raise "Formatting Error"
 			end	
 		end	
 	end	

 	#  ISO 3166:1993  four letter
 	# ISO 639-1  two letter
 	def self.get_domain_code(filename)
 		#filename must have an underscore starts with domain as one word
 		if filename.include?("_")
 			#looks for first _
 			return filename.slice(0, filename.index('_') ).upcase
 		else
 			raise "Domain error"
 		end		
 	end


 	## SEARCH FEATURES

 	def self.search(term)
    	where("source_content like :term", term: "%#{term}%")
  	end


 	
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController

def import
  #use carrierwave for more permanent storage e.g. TMX
  #class action (import) in model to handle behavior

  @project = Project.find(params[:project_id])
  
  Translation.set_ids(current_user, @project)

  Translation.import(params[:file])
  @translations = @project.translations
  flash[:notice] = t(:translations_imported, :default => "Translations imported" ) 
  redirect_to user_project_translations_path(@current_user, @project)

end



def index
  #display translations for a project
 @user = current_user
 @project = Project.find(params[:project_id])
 #eager loading?? languages, domains, users 
 @translations = @project.translations.find(:all, :include => [:owner, :source_lang, :target_lang, :domain]) 
 #all translations
 # @translations = Translation.order('created_at desc')

end

def edit

	@translation= Translation.find(params[:id])
end

  def update
    @translation = Translation.find(params[:id])

    respond_to do |format|
      if @translation.update_attributes(params[:translation])
        format.html { redirect_to @translation, notice: 'Translation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @translation = Translation.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @translation }
    end
  end

def new

  #from railsrecipes recipe 22
  @user = current_user
  @project = Project.find(params[:project_id])
  @translation = Translation.new

  #get project 
  #if GUEST? all projects where public true
  #get user
  # @project = current_user.projects.build
 
  # @project = current_user.projects.build(params[:project])

  # @translation.owner_id = current_user.id
  # @translation.project_id = Project.find_by_id(params[:project_id]).id

  
  # @translation = Translation.new
  # # @project = Project.find(params[:id])
  # @translations = @project.translations

 # @translation = Translation.new

#redisify all Language and Domain stuff
 @preferedlang = Language.find_by_id(@project.source_lang_id)
 @slanguages = Language.where("id != ?", @preferedlang.id).order('iso_code asc') 
 #puts project source in first position
 @slanguages.unshift(@preferedlang)
 #also in projec controller
 @mostpopulartarlang = Language.find_by_id(@project.translations.maximum("source_lang_id"))
 if @mostpopulartarlang
    @tlanguages = Language.where("id != ?", @mostpopulartarlang.id).order('iso_code asc')
    @tlanguages.unshift(@mostpopulartarlang)
 else
    @tlanguages = Language.order('iso_code desc')
 end 


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @translation }
    end
end


#version 1 - 1 domain per translation
#version 2 - mutliselect to create X translations of same content, one for each domain
def create
  @user = current_user
  @project = Project.find(params[:project_id])
  @preferedlang = Language.find_by_id(@project.source_lang_id)
  @slanguages = Language.where("id != ?", @preferedlang.id).order('iso_code asc') 
  @slanguages.unshift(@preferedlang)
 #from railsrecipes recipe 22 - refactor
  # @user = current_user


 @mostpopulartarlang = Language.find_by_id(@project.translations.maximum("source_lang_id"))
 if @mostpopulartarlang
    @tlanguages = Language.where("id != ?", @mostpopulartarlang.id).order('iso_code asc')
    @tlanguages.unshift(@mostpopulartarlang)
 else
    @tlanguages = Language.order('iso_code desc')
 end


  @translation = @project.translations.build(params[:translation])
  @translation.owner_id = @user.id

# @project = Project.find(params[:id])

#  @translation = Translation.new(params[:translation])
#  @translation.owner_id = current_user.id
# @translation.project_id = Project.find_by_id(params[:project_id]).id
  # @user = User.find(params[:user_id])
  # @project = Project.find(params[:project_id])
  # @translation = Translation.new(params[:translation])
  # @project = current_user.projects.build
  # @translation = @project.translations.build
  # @user = current_user
  # @project = Project.find_by_user_id(@user)
  # @translation = @project.translations.build(params[:translation])
  @languages = Language.all(:order => 'iso_code')
  #  #process information from checkbox

  if @translation.save
    flash[:notice] = "Translation was successfully created"
    # redirect_to user_project_translations_path(@user, @project)
    redirect_to user_project_path(current_user, @project)
  else
    render 'new'
  end
end

end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/translations/_batch.html.erb
<div id="batchform">
      <h2>Batch Import Translations</h2>
      <%= form_tag(import_user_project_translations_path(current_user, @project), multipart: true) do %>
        <%= file_field_tag :file %>
        <%= submit_tag "Import" %>
      <% end %>
</div>

app/views/translations/_form.html.erb
<%= simple_form_for [@user, @project, @translation], :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Translation</legend>

    <%= f.association :source_lang, :collection => @slanguages, 
            :include_blank => false, :label_method => :iso_code, :input_html => {:size => 1 } 
    %>
    <%= f.input :source_content %>
    <%= f.association :target_lang, :collection => @tlanguages, 
            :label_method => :iso_code, :include_blank => false, :input_html => {:size => 1 } %>

    <%= f.input :target_content %>
    <%= f.association :domain, :as => :radio_buttons  %>

    <%= f.association :source, :label_method => :url, :placeholder => 'make this a look ahead field - select or input', :prompt => 'Choose an existing source', :input_html => {:size => 1 }  %>
  <%= f.error :base %>
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t(:goback, :default => "Go Back"), user_project_path(current_user, @project), :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/translations/_translation.html.erb
<% @owner= User.find_by_id(translation.owner_id) %>

<!-- <p>
  <b><%= Language.find_by_id(translation.source_lang_id).iso_code if not translation.source_lang_id.nil? %></b><br>
  <%= link_to translation.source_content, user_project_translation_path(current_user, @project, translation) %>
</p>

<p>
  <b><%= Language.find_by_id(translation.target_lang_id).iso_code if not translation.target_lang_id.nil? %></b><br>
  <%= link_to translation.target_content, user_project_translation_path(current_user, @project, translation) %>
</p>
   	<%= Domain.find_by_id(translation.domain_id).code  if not translation.domain_id.nil? %>
   <%= Source.find_by_id(translation.source_id).url if not translation.source_id.nil? %><br/>
    <%= translation.is_public? ? "public" : "private" %>
</p>
<div class="form-actions">

          <%= link_to 'Edit', edit_user_project_translation_path(current_user, @project, translation),  :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', user_project_translation_path(current_user, @project, translation), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
</div>

  <span class="timestamp">
    Created <%= time_ago_in_words(translation.created_at) %> ago by <%= @owner.name unless @owner.nil? %>
  </span>
</li> -->

<tr>
      <td><%= translation.source_content %> <%= Language.find_by_id(translation.source_lang_id).iso_code if not translation.source_lang_id.nil? %> </td>

      <td><%= translation.target_content %>  <%= Language.find_by_id(translation.target_lang_id).iso_code if not translation.target_lang_id.nil? %> </td>

       <td><%= Domain.find_by_id(translation.domain_id).code if not translation.domain_id.nil?  %></td>

       <td><%= Source.find_by_id(translation.source_id).url if not translation.source_id.nil?  %></td>

       <td><%= @owner.name  %></td>

      <td><%= translation.created_at.strftime("%B %e, %Y") %> by <%= @owner.name unless @owner.nil? %> </td>
      <td><%= translation.is_public ? "public" : "private"  %></td>
      <td>
        <!-- put this logic in translations feed page rather than project feed page -->
          <% if @owner.id == current_user.id %>
          <%= link_to 'Edit', edit_user_project_translation_path(@owner, @project, translation),  :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', user_project_translation_path(@owner, @project, translation), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
          <% end %>
      </td>
</tr>

app/views/translations/edit.html.erb
<%= render :partial => 'form' %>

app/views/translations/import.html.erb
<h2>Batch Import Translations</h2>

<%= form_tag import_translations_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/translations/index.html.erb
<% provide(:title, t(:projecttranslations, :default => "Project Translations") )%>

<h1>Translations</h1>



TABLE NEEDS TO RESIZE TO CONTENT
de  source_content
en  target_content
domain created_at [owner_id] 
COLORED for isTerm
COLORED PUBLIC?

SOURCE- iterate over all sources for translation_id
if it looks like a link, put in a link tag

THIS TABLE IS FOR PUBLIC ACCESS TO TRANSLATIONS??

DATA TABLES!

<table class="table table-striped">

  <tbody>
    <% @translations.each do |translation| %>
    <% @owner= User.find_by_id(translation.owner_id) %>
      <tr>
        <td><%= Language.find_by_id(translation.source_lang_id).iso_code if not translation.source_lang_id.nil? %>
        <%= link_to translation.source_content, user_project_translations_path(translation) %></td>
    
        <td><%= Language.find_by_id(translation.target_lang_id).iso_code if not translation.target_lang_id.nil? %>
        <%= link_to translation.target_content, user_project_translations_path(translation)  %></td>

        <td><%=  Domain.find_by_id(translation.domain_id).code if not translation.domain_id.nil? %>
       
        <!-- TODO: if source url is a url, show as a link-->
        <%= Source.find_by_id(translation.source_id).url if not translation.source_id.nil? %>
        <%= translation.is_public? ? "public" : "private" %>

      </td>
        <td>
    
          <%= link_to 'Edit', edit_user_project_translation_path(current_user, @project, translation),  :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', user_project_translation_path(current_user, @project, translation), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>


        </td>
        <td>
            Created <%= time_ago_in_words(translation.created_at) %> ago by <%= @owner.name unless @owner.nil? %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_user_project_translation_path, :class => 'btn btn-primary' %>

app/views/translations/new.html.erb
	

<%= render :partial => 'form' %>

app/views/translations/show.html.erb
<h1>Translation</h1>

<p>
  <b><%= Language.find_by_id(@translation.source_lang_id).iso_code if not @translation.source_lang_id.nil? %></b><br>
  <%= link_to translation.source_content, translation_path(translation) %>
</p>

<p>
  <b><%= Language.find_by_id(translation.target_lang_id).iso_code if not translation.target_lang_id.nil? %></b><br>
  <%= link_to translation.target_content, translation_path(translation) %>
</p>
   	<%= Domain.find_by_id(translation.domain_id).code if not translation.domain_id.nil? %> ||
   <%= Source.find_by_id(translation.source_id).url if not translation.source_id.nil? %> ||
   <%= translation.created_at %><br/>
</p>
<div class="form-actions">
          <%= link_to 'Edit', edit_translation_path(translation), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', translation_path(translation), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
</div>