config/routes.rb
Termz::Application.routes.draw do
devise_for :users
  

  
   root to: 'pages#home'

  

  resources :users do
      resources :projects do
            resources :translations do
               collection { post :import }
            end
      end
  end

 
  

  get "pages/home"

  get "pages/about"

  get "pages/contact"

  get "pages/search"

      
  match '/home', to: 'pages#home'
  match '/about', to: 'pages#about'
  match '/contact', to: 'pages#contact'
  match '/search', to: 'pages#search'

  resources :domains

 

   

end

app/models/domain.rb
# == Schema Information
#
# Table name: domains
#
#  id        :integer          not null, primary key
#  name      :string(255)
#  code      :string(255)
#  image_url :string(255)
#  ancestry  :string(255)
#

class Domain < ActiveRecord::Base
  attr_accessible :code, :image_url, :name

  has_ancestry	
  # a translation has one domain (but same sc tc with different domain is a different translation!)
  belongs_to :translation


end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController

	#no new, create or update

	def index
		@domains = Domain.all
  	end

  	def show
  		@domain = Domain.find(params[:id])
		
  	end

end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/index.html.erb
SHOW ALL DOMAINS HERE WITH LINKS

<table>
  <tr>
  	<th></th>
    <th>Code</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @domains.each do |domain| %>
  <tr>
  	<td><%= image_tag domain.image_url %></td>
    <td><%= domain.code %></td>
    <td><%= domain.name %></td>

    <td><%= link_to 'Show', domain %></td>
    <td><%= link_to 'Edit', edit_domain_path(domain) %></td>
    <td><%= link_to 'Destroy', domain, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/domains/show.html.erb
show all translations for the @domain 