config/routes.rb
Termz::Application.routes.draw do
devise_for :users
  

  
   root to: 'pages#home'

  

  resources :users do
      resources :projects do
            resources :translations do
               collection { post :import }
            end
      end
  end

 
  

  get "pages/home"

  get "pages/about"

  get "pages/contact"

  get "pages/search"

      
  match '/home', to: 'pages#home'
  match '/about', to: 'pages#about'
  match '/contact', to: 'pages#contact'
  match '/search', to: 'pages#search'

  resources :domains

 

   

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  source_lang_id :integer
#  access_token   :string(255)
#  user_id        :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Project < ActiveRecord::Base

  attr_accessible :name, :source_lang_id

  before_save :generate_access_token


  validates :user_id, presence: true
  validates_uniqueness_of :name, :scope => :user_id

  has_many :translations
  
  #has own owner, ultimately may have several users attached to the project
  belongs_to :user

  belongs_to :source_lang, :class_name => 'Language'


  default_scope order: 'projects.created_at DESC' 





	private
  
     def generate_access_token
       #also handles duplicates, self because refers to group not instance var
       begin
         self.access_token = SecureRandom.urlsafe_base64(5)
       end while self.class.exists?(access_token: access_token)
    end



end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

##restrict this page to logged in users who own the projects
before_filter :authenticate_user!

def new
	@project = Project.new
	@languages = Language.all(:order => 'iso_code')

end


def show
	#show the project for this user

    # @translations all translations from all projects
	@project = Project.find(params[:id])
  @projectlang = Language.find_by_id(@project.source_lang_id).iso_code
	# @translations = @project.translations
  #eager? NO! all where project_id, user_id current_user
  # @translations = @project.translations.find(:all, :include => [:owner, :source_lang, :target_lang, :domain])
  @translations = Translation.includes(:owner, :source_lang, :target_lang, :domain).where("owner_id = ? and project_id = ?", current_user, @project.id)

  @languages = Language.all(:order => 'iso_code')
  @owner = User.find_by_id(@project.user_id)
  @projectcreatedat = @project.created_at
  @mostpopulartarlang = Language.find_by_id(@project.translations.maximum("source_lang_id"))
end


def create
  @project = current_user.projects.build(params[:project])
  @languages = Language.all(:order => 'iso_code')
  if @project.save
    flash[:notice] = t(:project_was_created_ok, :default=> "Project was created successfully")
    redirect_to user_projects_path
  else
    render 'new'
  end
end


def index
  #display all projects for a particular user
  @projects = current_user.projects
  #all users translations
  @allusertrans = current_user.translations
  @allusertrans_count = @allusertrans.size
end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project.html.erb
<li>
  <span class="content"><%= link_to project.name, user_project_path(project) %></span>
  <span class="timestamp">
    Created <%= time_ago_in_words(project.created_at) %> ago.
  </span>
</li>

app/views/projects/index.html.erb
<div id="projectlist">
		<h1>My projects</h1>

		<ul class="projects">
		  <% @projects.each do |project| %>
		    <li>
		      <%= link_to project.name, user_project_path(current_user, project) %>
		    </li>
		  <% end %>
		</ul>

		<p><%= link_to "New Project", new_user_project_path %></p>

</div>

<div id="my translations">
<h1>My Translations</h1>
SEARCH BOX

LIST OF ALL TRANSLATIONS 

SAME AS PROJECT SEARCH EXCEPT ALL TRANSLATIONS
<br />

Number of Translations: <%= @allusertrans_count %> 


<table id="translations" class="table table-striped">
<thead>
  <tr>
<th>Source Language </th>
      <th>Target Language</th>
      <th>Domain</th>
      <th>Source</th>
      <th>Owner</th>
      <th>Created on?</th>
      <th>Public?</th>
      <th>Links</th>
    </tr>
</thead>
<tbody>
  <%= @alltranslations %>
</tbody>
</table>
<br />


</div>		

app/views/projects/new.html.erb
###AUTOCOMPLETE ON LANGUAGES use REDIS to store languages (domains, all simple stuff)

<%= simple_form_for [@user, @project], :url => user_projects_path(current_user), :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Project</legend>
	  <%= f.input :name %>
	  <%= f.association :source_lang, :label => t(:source_language, :default=> "Source language"), :collection => @languages, :include_blank => false, :label_method => :name, :input_html => {:size => 1 } %>
   <%= f.error :base %>
	  <div class="form-actions">
      <%= f.submit t('project.new.submit_button', :default=> "Create Project"), :class => 'btn btn-primary' %>
   	</div>
  </fieldset>
<% end %>

app/views/projects/show.html.erb
<div class="row">
  <aside class="span6">
    <section>
      <h2> Project Info </h2>
      <h1>
        <%= t(:projectname, :default=> "Project name:") %> <%= @project.name %><br/>
        <%= t(:projectlang, :default=> "Project language:") %> <%= @projectlang %><br/>
        <%= t(:projectowner, :default=> "Owner:") %> <%= @owner.name %><br/>
        <%= t(:projectaccess, :default=> "Access token:") %> <%= @project.access_token %><br/>
        <%= t(:projectcreated_at, :default=> "Created:") %> <%= @projectcreatedat.strftime("%B %d, %Y") %><br/>
        <%= t(:projecttranslationscount, :default=> "Number of translations:") %> <%= @project.translations.count %><br/>
        <% if @project.translations.count >0 %>
        <%= t(:projectstats_maxtargetlang, 
                :default=> "Most popular target language:") %> <%= @mostpopulartarlang.name if @mostpopulartarlang %>
            <br/>
        <% end %>        
        
        <%= t(:projectsubscriberscount, :default=> "Number of subscribers:") %> 0
      </h1>
    </section>
  </aside>
</div>
<section>
<h2> Options </h2>
<div class="buttons">
	
	<%= link_to 'Back to Projects/Translation', user_projects_path(current_user), :class => 'btn btn-primary' %>
	<%= link_to 'Get more translations', pages_search_path, :class => 'btn btn-primary' %>

</div>	

</section>


<h2> My Translations for this Project </h2>

MAXIMUM 1000 then Create New Project

<table id="translations" class="table table-striped">
<thead>
  <tr>
<th>Source Language </th>
      <th>Target Language</th>
      <th>Domain</th>
      <th>Source</th>
      <th>Owner</th>
      <th>Created on?</th>
      <th>Public?</th>
      <th>Links</th>
    </tr>
</thead>
<tbody>
    <%= render @translations %> 
</tbody>
</table>
<br />
<%= link_to 'New Translation', new_user_project_translation_path(current_user, @project), :class => 'btn btn-small' %>


<br />

<div id="translationbatchentry">

<button id="batch">Toggle Translation Batch Entry</button>

    <%= render :partial => 'translations/batch' %>


<script>
$("button#batch").click(function () {
$("#batchform").toggle("slow");
});

$("button#search").click(function () {
$("#searchbox").toggle("slow");
});

</script>

</div>