config/routes.rb
Termz::Application.routes.draw do
devise_for :users
  

  
   root to: 'pages#home'

  

  resources :users do
      resources :projects do
            resources :translations do
               collection { post :import }
            end
      end
  end

 
  

  get "pages/home"

  get "pages/about"

  get "pages/contact"

  get "pages/search"

      
  match '/home', to: 'pages#home'
  match '/about', to: 'pages#about'
  match '/contact', to: 'pages#contact'
  match '/search', to: 'pages#search'

  resources :domains

 

   

end

app/views/layouts/_flashcontent.html.erb
<!-- 	<% if flash[:notice] %>
		<div id="notice" class="message">
			<%= flash[:notice] %>
    	</div>
  	<% elsif flash[:alert] %>
  		<div id="alert" class="message">
			<%= flash[:alert] %>
    	</div>
  <% end %> -->


<!--   <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %> -->

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://termz.org/">Termz</a>
    by SD PLATT
  </small>
  
</footer>

app/views/layouts/_headernav.html.erb
<nav>
            <ul class="nav pull-right">

              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "Search",    search_path %></li>

              <% if user_signed_in? %>
                  <li> <%= link_to "Profile", user_path(current_user) %></li>
                  <li> <%= link_to "Projects", user_projects_path(current_user) %></li>
              <% else %>
                  <li><%= link_to "Sign in", new_user_session_path  %></li>     
              <% end %>
               <% if user_signed_in? %>
              		<li> <%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
              <% else %>	 
               		<li><%= link_to "Sign up", new_user_registration_path  %></li>
              <% end %>
           
            </ul>
</nav>

<div id="loggedinas">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Termz | <%= yield(:title) %> </title>

   <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
 <meta name="viewport" content="width=device-width, initial-scale=1.0">


</head>
<body>

 <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "TERMZ", root_path, id: "logo" %>
            <%= render 'layouts/headernav' %>
        </div>
      </div>
  </header>

  <!-- fixed witdh versus container-fluid -->
  <div class="container">
<!--     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
 -->
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

     <div class="row">
      <div class="span11">

        <%= yield %>

      </div>
<!--       <div class="span3">
        <h2>About Us</h2>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </div>
 -->    </div>




    
    
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>

</div>
</body>
</html>